version: '3.7'

services:

  mysql-confluence:
    image: mysql:5.7
    container_name: mysql-confluence
    environment:
      - MYSQL_ROOT_PASSWORD=devops
      - MYSQL_DATABASE=confluencedb
      - MYSQL_USER=confluence
      - MYSQL_PASSWORD=devops
    networks:
      - devops
    volumes:
      - ./mysql/mysqld_confluence.cnf:/etc/mysql/conf.d/mysqld_confluence.cnf
      - mysql-confluence:/var/lib/mysql
    command: ["--transaction-isolation=READ-COMMITTED"]

  confluence:
    image: atlassian/confluence-server
    container_name: confluence
    hostname: confluence
    depends_on:
      - mysql-confluence
    ports:
      - "8090:8090"
      - "8091:8091"
    networks:
      - devops
    environment:
#     - JVM_MINIMUM_MEMORY=512m                 # 384m
#     - JVM_MAXIMUM_MEMORY=2048m                # 768m
      - ATL_PROXY_NAME=docs.example.com
      - ATL_PROXY_PORT=443
    volumes:
      - confluence:/var/atlassian/application-data/confluence
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  devops:
    name: devops

volumes:
  mysql-confluence:
    name: mysql-confluence
  confluence:
    name: confluence
    
    
    
