version: "3"

services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    hostname: jenkins.trustchain.com
    privileged: true
    user: 0:0
    dns:
      - 172.31.0.254
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /srv/jenkins:/var/jenkins_home
